### ISSUE TITLE
custom meta models is not allow to draw

### ISSUE THREAD

**Issue by ThanrayTian** [bpmn-io/bpmn-js-example-model-extension#2]
@nikku 
I defined a Cat Model like this (type 'Cat' is not inherited from 'Element' or 'bpmn:Task'):
<pre>
{
  "name": "Cats",
  "uri": "http://cat",
  "prefix": "c",
  "types": [
    {
      "name": "Base",
      "properties": [
        { "name": "id", "type": "String", "isAttr": true }
      ]
    },
    {
      "name": "Cat",
      "superClass": [ "Base" ],
      "properties": [
        { "name": "name", "type": "String", "isAttr": true, "default": "No Name" },
        { "name": "age", "type": "Integer", "isAttr": true }
      ]
    }
  ]
}
</pre>

and then I modified the [https://github.com/bpmn-io/bpmn-js-nyan](url) example.

<pre>
this.modeler = new Modeler({
      container: container,
      additionalModules: [
        resizeModule,
        colorPickerModule,
        nyanDrawModule,
        nyanPaletteModule
      ],
      moddleExtensions: {
        c: catModdleExtension
      }
    })
</pre>

In NyanPaletteProvider.js:
<pre>
var serviceTaskShape = elementFactory.create(
  // 'shape', { type: 'bpmn:ServiceTask' }
  'shape', { type: 'c:Cat' }
)
</pre>

In NyanRenderer.js:
<pre>
this.canRender = function (element) {
  // return is(element, 'bpmn:ServiceTask')
  return is(element, 'c:Cat')
}
</pre>

and result was：

![draw_failed](https://user-images.githubusercontent.com/9781603/64308939-982f6900-cfcd-11e9-8e11-b333f8c4b0dc.gif)

What should I do to make it work?

**Comment by ThanrayTian** [comment]
And then I change the SuperClass of 'Cat' to 'bpmn:Task' and it works...

Is this necessary?

Or I can add custom rules to achieve ?

**Comment by nikku** [comment]
You have to add custom rules, cf. [custom modeling rules](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-modeling-rules).

We encourage you to build your customizations on top of the elements defined in the BPMN spec though. So making it a sub-class of `bpmn:Task` is a valid option. Only then the cat can properly be added to the underlying XML structures.
